spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: wyx151425

mybatis:
  configuration:
    use-generated-keys: true
    use-column-label: true
    map-underscore-to-camel-case: true
  type-aliases-package: cn.edu.cnu.zhanghao.model.pojo
  mapper-locations: classpath:mappers/*.xml

logging:
  level:
    cn.edu.cnu.zhanghao.repository: debug
